version: '3.4'

services:
  arcadia.arcadiabackend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  arcadia.arcadiafrontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
